server:
  port: 6060

auth:
  domain: YOUR-AUTH0-DOMAIN
  audience: https://hello-world.example.com

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth.domain}/
